export const GAME_LOOP_DELAY = 10;

export const CELL_SIZE = 16;

export const PLAYER_HEIGHT = 32;
export const PLAYER_WIDTH = 16;

export const PLAYER_BASE_SPEED = 0.2;

export const PICKAXE_RANGE = 2;

export const STATIC_MAP =
  'X                                                                      X\n' +
  'X                                                                      X\n' +
  'X                                                                      X\n' +
  'X                                                                      X\n' +
  'X                                                                      X\n' +
  'X                                                                      X\n' +
  'X                                                                      X\n' +
  'X                                                                      X\n' +
  'X                                                                      X\n' +
  'X                                                     DDDDDDD          X\n' +
  'X                                                   DDDDDDDDDDD        X\n' +
  'X    DD       S       DDD                        DDDDDDDDDDDDDDDD      X\n' +
  'XDDDDDDDDDDDDDDDDDDDDDDDDD                   DDDDDDDDDDDDDDDDDDDDDDDDDDX\n' +
  'XXXXXXXXXXXXXXXXXXXXXXXXXXDD                DDXXXXXXXXXXXXXXXXXXXXXXXXXX\n' +
  'XXXXXXXXXXXXXXXXXXXXXXXXXXXXDD              DDXXXXXXXXXXXXXXXXXXXXXXXXXX\n' +
  'XXXXXXXXXXXXXXXXXXXXXXXXXXXXDD   DDDDDDD    DDXXXXXXXXXXXXXXXXXXXXXXXXXX\n' +
  'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXDD  DDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n' +
  'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXDD XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n' +
  'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n' +
  'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n' +
  'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n' +
  'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n' +
  'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n' +
  'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n' +
  'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n' +
  'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n' +
  'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n' +
  'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n' +
  'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n' +
  'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n' +
  'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n' +
  'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n' +
  'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n' +
  'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n' +
  'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n' +
  'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n' +
  'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
